const city = {
  "Guildhall": "Centers of commerce where trades like blacksmithing, weaving, and masonry are regulated by guilds. Often a place for artisans to set prices, train apprentices, and ensure trade quality.",
  "Bathhouse": "Public places used for bathing, relaxation, and socializing. In Faerûn, this could be a luxurious place for nobles and merchants to meet.",
  "Public Forum": "An open space for town citizens to gather for discussions, trade, or political meetings. In Faerûn, it could be a place for town councils or public trials.",
  "Aqueduct": "A system for bringing fresh water into the town, often magically enhanced by wizards or druids in Faerûn.",
  "Clock Tower": "A town landmark symbolizing wealth and technological advancement. In Faerûn, this could be a magical timepiece that regulates the town's functions.",
  "Almshouse or Hospital": "A place where the sick or poor receive care, often run by temples devoted to gods like Ilmater or Lathander.",
  "Armory or Arsenal": "A storage facility for weapons and armor, necessary for the defense of the town. In Faerûn, this could also house magical weapons.",
  "Observatory": "A tower or building for studying celestial and magical events, often used by wizards in Faerûn.",
  "Apothecary": "A shop where herbalists and alchemists sell potions and remedies, often mixing magical potions with mundane cures.",
  "Theater or Amphitheater": "A cultural hub for performances, religious ceremonies, or bardic competitions. In Faerûn, it could also host magical performances.",
  "Prison or Dungeon": "A place to detain criminals, magical creatures, or dangerous beings. Often located beneath castles or guardhouses in Faerûn.",
  "Windmill or Watermill": "Used for grinding grain or powering machinery. In Faerûn, these mills could be magically enhanced for greater efficiency.",
  "Graveyard": "A solemn place dedicated to the burial of the dead, often consecrated to gods like Kelemvor. Could contain the tombs of heroes or ancient artifacts.",
  "Shipyard": "A coastal or river location where ships are built or repaired. In Faerûn, shipyards in cities like Baldur's Gate would be vital for trade and defense.",
  "Marketplace": "The commercial heart of a town where merchants trade goods, food, and magical items. In Faerûn, marketplaces are hubs for news and commerce.",
  "Temple or Shrine": "Dedicated to the worship of deities such as Chauntea, Lathander, or Mystra. Temples are often linked to local governance or charity.",
  "Barracks/Guardhouse": "The center for local defense forces. In Faerûn, this would be where guards or militias are housed and trained, possibly containing magical defenses.",
  "Inn/Tavern": "A place for locals and travelers to rest, drink, and exchange news. In Faerûn, this could be a hotspot for adventurers.",
  "Blacksmith": "Provides tools, weapons, and armor for the town. In Faerûn, blacksmiths could also craft enchanted items.",
  "Library or Wizard's Tower": "A place of learning and research. In Faerûn, these could store ancient tomes and magical knowledge.",
  "Schoolhouse": "A place for education and training. In Faerûn, schools might teach mundane subjects or magic.",
  "Watchtower": "A defensive structure placed to warn of approaching threats. In Faerûn, a watchtower could be enchanted to detect magical or extraplanar dangers.",
  "Farms/Orchards": "Fields and orchards that provide food for the town. In Faerûn, these could be magically enhanced to yield larger harvests."
}

