const eco = [
  {
    "rank": 1,
    "city": "Waterdeep",
    "realm": "Sword Coast",
    "population": 132661,
    "ships_daily": 39,
    "wagons_daily": 220,
    "bank_assets_gp": 45104740,
    "export_index": 98,
    "mage_index": 28
  },
  {
    "rank": 2,
    "city": "Athkatla",
    "realm": "Amn",
    "population": 118804,
    "ships_daily": 35,
    "wagons_daily": 131,
    "bank_assets_gp": 40110606,
    "export_index": 97,
    "mage_index": 28
  },
  {
    "rank": 3,
    "city": "Calimport",
    "realm": "Calimshan",
    "population": 192787,
    "ships_daily": 57,
    "wagons_daily": 159,
    "bank_assets_gp": 61782039,
    "export_index": 95,
    "mage_index": 28
  },
  {
    "rank": 4,
    "city": "Selgaunt",
    "realm": "Sembia",
    "population": 55000,
    "ships_daily": 17,
    "wagons_daily": 61,
    "bank_assets_gp": 31339000,
    "export_index": 93,
    "mage_index": 12
  },
  {
    "rank": 5,
    "city": "Westgate",
    "realm": "Dragon Coast",
    "population": 43000,
    "ships_daily": 16,
    "wagons_daily": 43,
    "bank_assets_gp": 24594500,
    "export_index": 92,
    "mage_index": 12
  },
  {
    "rank": 6,
    "city": "Baldur’s Gate",
    "realm": "Western Heartlands",
    "population": 42000,
    "ships_daily": 16,
    "wagons_daily": 69,
    "bank_assets_gp": 23478000,
    "export_index": 90,
    "mage_index": 12
  },
  {
    "rank": 7,
    "city": "Skuld",
    "realm": "Mulhorand",
    "population": 125000,
    "ships_daily": 18,
    "wagons_daily": 138,
    "bank_assets_gp": 74375000,
    "export_index": 88,
    "mage_index": 28
  },
  {
    "rank": 8,
    "city": "Suzail",
    "realm": "Cormyr",
    "population": 26000,
    "ships_daily": 10,
    "wagons_daily": 29,
    "bank_assets_gp": 14442000,
    "export_index": 88,
    "mage_index": 12
  },
  {
    "rank": 9,
    "city": "Zhentil Keep",
    "realm": "Moonsea",
    "population": 26000,
    "ships_daily": 5,
    "wagons_daily": 47,
    "bank_assets_gp": 14442000,
    "export_index": 87,
    "mage_index": 12
  },
  {
    "rank": 10,
    "city": "Neverwinter",
    "realm": "North",
    "population": 23000,
    "ships_daily": 8,
    "wagons_daily": 25,
    "bank_assets_gp": 12673000,
    "export_index": 87,
    "mage_index": 12
  },
  {
    "rank": 11,
    "city": "Silverymoon",
    "realm": "Silver Marches",
    "population": 37000,
    "ships_daily": 0,
    "wagons_daily": 41,
    "bank_assets_gp": 19736000,
    "export_index": 86,
    "mage_index": 40
  },
  {
    "rank": 12,
    "city": "Mirabar",
    "realm": "North",
    "population": 23000,
    "ships_daily": 0,
    "wagons_daily": 25,
    "bank_assets_gp": 12221000,
    "export_index": 85,
    "mage_index": 12
  },
  {
    "rank": 13,
    "city": "Saerloon",
    "realm": "Sembia",
    "population": 54000,
    "ships_daily": 21,
    "wagons_daily": 59,
    "bank_assets_gp": 28224000,
    "export_index": 85,
    "mage_index": 12
  },
  {
    "rank": 14,
    "city": "Luskan",
    "realm": "North",
    "population": 16000,
    "ships_daily": 6,
    "wagons_daily": 18,
    "bank_assets_gp": 8208000,
    "export_index": 84,
    "mage_index": 28
  },
  {
    "rank": 15,
    "city": "Telflamm",
    "realm": "Thesk",
    "population": 15000,
    "ships_daily": 6,
    "wagons_daily": 25,
    "bank_assets_gp": 7545000,
    "export_index": 84,
    "mage_index": 12
  },
  {
    "rank": 16,
    "city": "Cimbar",
    "realm": "Chessenta",
    "population": 34000,
    "ships_daily": 14,
    "wagons_daily": 37,
    "bank_assets_gp": 16772000,
    "export_index": 83,
    "mage_index": 12
  },
  {
    "rank": 17,
    "city": "Alaghon",
    "realm": "Turmish",
    "population": 45000,
    "ships_daily": 18,
    "wagons_daily": 50,
    "bank_assets_gp": 21915000,
    "export_index": 83,
    "mage_index": 12
  },
  {
    "rank": 18,
    "city": "Scornubel",
    "realm": "Western Heartlands",
    "population": 9000,
    "ships_daily": 0,
    "wagons_daily": 15,
    "bank_assets_gp": 4302000,
    "export_index": 82,
    "mage_index": 12
  },
  {
    "rank": 19,
    "city": "Port Nyanzaru",
    "realm": "Chult",
    "population": 12000,
    "ships_daily": 5,
    "wagons_daily": 13,
    "bank_assets_gp": 5472000,
    "export_index": 82,
    "mage_index": 12
  },
  {
    "rank": 20,
    "city": "Yhaunn",
    "realm": "Sembia",
    "population": 35000,
    "ships_daily": 13,
    "wagons_daily": 39,
    "bank_assets_gp": 15890000,
    "export_index": 82,
    "mage_index": 12
  },
  {
    "rank": 21,
    "city": "Urmlaspyr",
    "realm": "Sembia",
    "population": 27000,
    "ships_daily": 10,
    "wagons_daily": 30,
    "bank_assets_gp": 12183000,
    "export_index": 81,
    "mage_index": 12
  },
  {
    "rank": 22,
    "city": "Zazesspur",
    "realm": "Tethyr",
    "population": 55000,
    "ships_daily": 22,
    "wagons_daily": 61,
    "bank_assets_gp": 24216500,
    "export_index": 81,
    "mage_index": 12
  },
  {
    "rank": 23,
    "city": "Darromar",
    "realm": "Tethyr",
    "population": 44000,
    "ships_daily": 0,
    "wagons_daily": 49,
    "bank_assets_gp": 19316000,
    "export_index": 80,
    "mage_index": 12
  },
  {
    "rank": 24,
    "city": "Tantras",
    "realm": "Vast",
    "population": 29000,
    "ships_daily": 11,
    "wagons_daily": 32,
    "bank_assets_gp": 12464000,
    "export_index": 80,
    "mage_index": 12
  },
  {
    "rank": 25,
    "city": "Raven’s Bluff",
    "realm": "Vast",
    "population": 40000,
    "ships_daily": 16,
    "wagons_daily": 43,
    "bank_assets_gp": 17176000,
    "export_index": 80,
    "mage_index": 12
  },
  {
    "rank": 26,
    "city": "Procampur",
    "realm": "Vast",
    "population": 42000,
    "ships_daily": 17,
    "wagons_daily": 45,
    "bank_assets_gp": 17682000,
    "export_index": 79,
    "mage_index": 12
  },
  {
    "rank": 27,
    "city": "Sarshel",
    "realm": "Impiltur",
    "population": 17000,
    "ships_daily": 7,
    "wagons_daily": 19,
    "bank_assets_gp": 7138000,
    "export_index": 79,
    "mage_index": 12
  },
  {
    "rank": 28,
    "city": "Hillsfar",
    "realm": "Moonsea",
    "population": 14000,
    "ships_daily": 0,
    "wagons_daily": 23,
    "bank_assets_gp": 5720000,
    "export_index": 78,
    "mage_index": 12
  },
  {
    "rank": 29,
    "city": "Teziir",
    "realm": "Dragon Coast",
    "population": 17000,
    "ships_daily": 7,
    "wagons_daily": 19,
    "bank_assets_gp": 6933000,
    "export_index": 78,
    "mage_index": 12
  },
  {
    "rank": 30,
    "city": "Arrabar",
    "realm": "Chondath",
    "population": 22000,
    "ships_daily": 4,
    "wagons_daily": 27,
    "bank_assets_gp": 8866000,
    "export_index": 78,
    "mage_index": 12
  },
  {
    "rank": 31,
    "city": "Hlondeth",
    "realm": "Vilhon Reach",
    "population": 32000,
    "ships_daily": 5,
    "wagons_daily": 35,
    "bank_assets_gp": 12307200,
    "export_index": 77,
    "mage_index": 12
  },
  {
    "rank": 32,
    "city": "Halarahh",
    "realm": "Halruaa",
    "population": 31000,
    "ships_daily": 11,
    "wagons_daily": 34,
    "bank_assets_gp": 11724000,
    "export_index": 77,
    "mage_index": 40
  },
  {
    "rank": 33,
    "city": "Mithral Hall",
    "realm": "North",
    "population": 8000,
    "ships_daily": 0,
    "wagons_daily": 13,
    "bank_assets_gp": 2968000,
    "export_index": 76,
    "mage_index": 12
  },
  {
    "rank": 34,
    "city": "Citadel Adbar",
    "realm": "North",
    "population": 14000,
    "ships_daily": 0,
    "wagons_daily": 15,
    "bank_assets_gp": 5122000,
    "export_index": 76,
    "mage_index": 12
  },
  {
    "rank": 35,
    "city": "Citadel Felbarr",
    "realm": "Silver Marches",
    "population": 6700,
    "ships_daily": 0,
    "wagons_daily": 7,
    "bank_assets_gp": 2338000,
    "export_index": 75,
    "mage_index": 12
  },
  {
    "rank": 36,
    "city": "Menzoberranzan",
    "realm": "Underdark",
    "population": 24000,
    "ships_daily": 0,
    "wagons_daily": 0,
    "bank_assets_gp": 7952000,
    "export_index": 71,
    "mage_index": 40
  },
  {
    "rank": 37,
    "city": "Skullport",
    "realm": "Undermountain",
    "population": 2000,
    "ships_daily": 0,
    "wagons_daily": 0,
    "bank_assets_gp": 628000,
    "export_index": 70,
    "mage_index": 28
  },
  {
    "rank": 38,
    "city": "Bezantur",
    "realm": "Thay",
    "population": 42000,
    "ships_daily": 17,
    "wagons_daily": 46,
    "bank_assets_gp": 12768000,
    "export_index": 70,
    "mage_index": 40
  },
  {
    "rank": 39,
    "city": "Eltabbar",
    "realm": "Thay",
    "population": 34000,
    "ships_daily": 4,
    "wagons_daily": 37,
    "bank_assets_gp": 10178000,
    "export_index": 69,
    "mage_index": 28
  },
  {
    "rank": 40,
    "city": "Airspur",
    "realm": "Chessenta",
    "population": 28000,
    "ships_daily": 11,
    "wagons_daily": 31,
    "bank_assets_gp": 8060000,
    "export_index": 69,
    "mage_index": 28
  },
  {
    "rank": 41,
    "city": "Myratma",
    "realm": "Tethyr",
    "population": 21000,
    "ships_daily": 8,
    "wagons_daily": 23,
    "bank_assets_gp": 6061000,
    "export_index": 68,
    "mage_index": 12
  },
  {
    "rank": 42,
    "city": "Lyrabar",
    "realm": "Impiltur",
    "population": 19000,
    "ships_daily": 7,
    "wagons_daily": 21,
    "bank_assets_gp": 5443000,
    "export_index": 68,
    "mage_index": 12
  },
  {
    "rank": 43,
    "city": "Tashluta",
    "realm": "Tashalar",
    "population": 15000,
    "ships_daily": 6,
    "wagons_daily": 17,
    "bank_assets_gp": 4200000,
    "export_index": 67,
    "mage_index": 12
  },
  {
    "rank": 44,
    "city": "Ormpetarr",
    "realm": "Sespech",
    "population": 16000,
    "ships_daily": 3,
    "wagons_daily": 27,
    "bank_assets_gp": 4760000,
    "export_index": 67,
    "mage_index": 12
  },
  {
    "rank": 45,
    "city": "Ithmong",
    "realm": "Lapaliiya",
    "population": 13000,
    "ships_daily": 5,
    "wagons_daily": 14,
    "bank_assets_gp": 3705000,
    "export_index": 76,
    "mage_index": 12
  },
  {
    "rank": 46,
    "city": "Sheirtalar",
    "realm": "Lapaliiya",
    "population": 38000,
    "ships_daily": 0,
    "wagons_daily": 42,
    "bank_assets_gp": 10830000,
    "export_index": 77,
    "mage_index": 12
  },
  {
    "rank": 47,
    "city": "Port Kir",
    "realm": "Tethyr",
    "population": 9000,
    "ships_daily": 4,
    "wagons_daily": 10,
    "bank_assets_gp": 2556000,
    "export_index": 77,
    "mage_index": 12
  },
  {
    "rank": 48,
    "city": "Murann",
    "realm": "Amn",
    "population": 17000,
    "ships_daily": 7,
    "wagons_daily": 19,
    "bank_assets_gp": 4836000,
    "export_index": 77,
    "mage_index": 12
  },
  {
    "rank": 49,
    "city": "Innarlith",
    "realm": "Lake of Steam",
    "population": 12000,
    "ships_daily": 5,
    "wagons_daily": 13,
    "bank_assets_gp": 3420000,
    "export_index": 96,
    "mage_index": 12
  },
  {
    "rank": 50,
    "city": "Heldapan",
    "realm": "Durpar",
    "population": 22000,
    "ships_daily": 5,
    "wagons_daily": 24,
    "bank_assets_gp": 4914360,
    "export_index": 78,
    "mage_index": 12
  }
];

