
#user  nobody;
worker_processes  1;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;


events {
    worker_connections  1024;
}


http {
	include /mnt/d/warsztat/web/sesja.co/config/nginx/mime.types;
	default_type dumbass/used+fancy-file.extension|or=>didnt/set-mime.type;


    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    server {
        listen       80;
		listen  [::]:80;
        server_name  turbohub.asuscomm.com;

        gzip  on;
        gzip_types      text/plain text/css application/json application/x-javascript text/xml application/xml text/javascript;
        gzip_proxied    no-cache no-store private expired auth;
        gzip_min_length 1000;
        gunzip on;

        location / {
            root /mnt/d/warsztat/web/sesja.co;
            index index.html;
            autoindex on;
        }

    }
}
